/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { NewsItem, StartupEvent, UserProfile, ChatMessage, AppNotification } from './types';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user-head-admin',
    name: 'Elena Rostova',
    email: 'admin@venturepulse.io',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    bio: 'Editorial Head & Verification Lead at VenturePulse. Overseeing startup sourcing and verification standards.',
    isApproved: true,
    emailVerified: true,
    password: 'password123',
    createdAt: '2026-01-10T08:00:00.000Z',
    lastActive: 'Just now',
  },
  {
    id: 'user-contributor-1',
    name: 'Marcus Chen',
    email: 'marcus.chen@techscout.co',
    role: 'uploader',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    bio: 'Silicon Valley tech reporter & angel syndicator. Tracking early stage AI infrastructure.',
    isApproved: true,
    emailVerified: true,
    password: 'password123',
    createdAt: '2026-02-01T10:30:00.000Z',
    lastActive: '5m ago',
  },
  {
    id: 'user-contributor-2',
    name: 'Dr. Sarah Jenkins',
    email: 'sjenkins@deeptechventures.org',
    role: 'uploader',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    bio: 'Deep tech researcher and policy advisor covering European grants and semiconductor spin-offs.',
    isApproved: true,
    emailVerified: true,
    password: 'password123',
    createdAt: '2026-02-15T14:20:00.000Z',
    lastActive: '1h ago',
  },
  {
    id: 'user-viewer-default',
    name: 'Alex Rivera',
    email: 'alex@foundercraft.xyz',
    role: 'viewer',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    bio: 'Second-time founder building in generative workflow automation. Community viewer.',
    isApproved: true,
    emailVerified: true,
    password: 'password123',
    createdAt: '2026-03-01T09:00:00.000Z',
    lastActive: 'Active now',
  },
];

export const INITIAL_NEWS: NewsItem[] = [
  // 1. Top Story / Launch & Funding
  {
    id: 'news-1',
    category: 'new-startups',
    headline: 'Anthropic Alum Unveils Synapse Core to Automate Microchip Photolithography',
    sourceName: 'TechCrunch',
    sourceUrl: 'https://techcrunch.com/category/startups/',
    publishDate: '2026-09-22T14:30:00.000Z',
    summary: 'Synapse Core officially launched out of stealth mode with $18M in initial seed funding to replace legacy optical proximity correction software with neural geometry generators for sub-2nm chip foundries.',
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&auto=format&fit=crop&q=80',
    fundingAmount: '$18,000,000',
    fundingRound: 'Seed',
    investors: ['Radical Ventures', 'Khosla Ventures', 'Lux Capital'],
    uploader: {
      id: 'user-contributor-1',
      name: 'Marcus Chen',
      role: 'uploader',
    },
    status: 'approved',
    automatedCheck: {
      urlResolves: true,
      dateRecent: true,
      categoryMatch: true,
      flagged: false,
      flagReasons: [],
      checkedAt: '2026-09-22T14:35:00.000Z',
      httpStatus: 200,
    },
    createdAt: '2026-09-22T14:35:00.000Z',
    sourceType: 'contributor-submission',
  },

  // 2. Scheme Card
  {
    id: 'news-2',
    category: 'new-schemes',
    headline: 'EU Innovation Council Injects €1.4B Under Updated 2026 Scale-Up DeepTech Scheme',
    sourceName: 'European Commission EIC',
    sourceUrl: 'https://eic.ec.europa.eu/eic-work-programme-2026_en',
    publishDate: '2026-09-21T09:15:00.000Z',
    summary: 'The European Innovation Council opened applications for its revised DeepTech Transition Grant, offering non-dilutive awards up to €2.5M alongside direct equity co-investment up to €15M for quantum computing, advanced materials, and clean propulsion.',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
    schemeOfferedBy: 'European Innovation Council (EIC)',
    schemeDeadline: 'October 15, 2026',
    schemeApplyUrl: 'https://eic.ec.europa.eu/eic-work-programme-2026_en',
    uploader: {
      id: 'user-contributor-2',
      name: 'Dr. Sarah Jenkins',
      role: 'uploader',
    },
    status: 'approved',
    automatedCheck: {
      urlResolves: true,
      dateRecent: true,
      categoryMatch: true,
      flagged: false,
      flagReasons: [],
      checkedAt: '2026-09-21T09:20:00.000Z',
      httpStatus: 200,
    },
    createdAt: '2026-09-21T09:20:00.000Z',
    sourceType: 'contributor-submission',
  },

  // 3. Funding Card (Large Amount, Round, Investors)
  {
    id: 'news-4',
    category: 'investor-activity',
    headline: 'Sequoia & Andreessen Horowitz Co-Lead $62M Series B in Cyber-Defense Agent Firm AegisNet',
    sourceName: 'Reuters',
    sourceUrl: 'https://www.reuters.com/technology/',
    publishDate: '2026-09-22T18:45:00.000Z',
    summary: 'AegisNet closed $62M on a $310M post-money valuation. Lead partner confirmed capital will finance sovereign cloud deployments across transatlantic NATO aerospace contractors and critical energy infrastructure.',
    imageUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&auto=format&fit=crop&q=80',
    fundingAmount: '$62,000,000',
    fundingRound: 'Series B',
    investors: ['Sequoia Capital', 'Andreessen Horowitz', 'Shield Capital', 'In-Q-Tel'],
    uploader: {
      id: 'user-contributor-1',
      name: 'Marcus Chen',
      role: 'uploader',
    },
    status: 'approved',
    automatedCheck: {
      urlResolves: true,
      dateRecent: true,
      categoryMatch: true,
      flagged: false,
      flagReasons: [],
      checkedAt: '2026-09-22T18:50:00.000Z',
      httpStatus: 200,
    },
    createdAt: '2026-09-22T18:50:00.000Z',
    sourceType: 'contributor-submission',
  },

  // 4. Problem & Fix Card (Two-Part Card)
  {
    id: 'news-6',
    category: 'emerging-problems',
    headline: 'Founders Face 300% Inference Cost Spikes: How 14 Engineering Leads Are Shifting to Quantized Edge Runtimes',
    sourceName: 'VentureBeat',
    sourceUrl: 'https://venturebeat.com/category/ai/',
    publishDate: '2026-09-22T07:20:00.000Z',
    summary: 'Surging compute consumption for multi-agent loops is squeezing early-stage SaaS gross margins down from 75% to single digits.',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
    problemContext: 'Continuous token generation across autonomous background agent loops causes sudden 300% AWS Bedrock and OpenAI bill increases, degrading software gross margins from 75% down to under 12%.',
    fixSolution: 'Technical teams are deploying 4-bit quantized speculative edge runtimes (llama.cpp/MLX) directly on client hardware for 80% of classification tasks, only invoking cloud models for final validation.',
    uploader: {
      id: 'user-head-admin',
      name: 'Elena Rostova',
      role: 'admin',
    },
    status: 'approved',
    automatedCheck: {
      urlResolves: true,
      dateRecent: true,
      categoryMatch: true,
      flagged: false,
      flagReasons: [],
      checkedAt: '2026-09-22T07:25:00.000Z',
      httpStatus: 200,
    },
    createdAt: '2026-09-22T07:25:00.000Z',
    sourceType: 'automated-ingestion',
  },

  // 5. Event Card (Date block, venue, add to calendar)
  {
    id: 'news-5',
    category: 'startup-events',
    headline: 'Y Combinator Fall 2026 Demo Day Announced for San Francisco with 240 Founder Pitches',
    sourceName: 'Y Combinator Blog',
    sourceUrl: 'https://www.ycombinator.com/blog/',
    publishDate: '2026-09-20T11:00:00.000Z',
    summary: 'Accredited global investors can apply for in-person and streaming passes to evaluate pitches spanning robotics, autonomous software engineering, and climate biotech founders.',
    imageUrl: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&auto=format&fit=crop&q=80',
    eventDate: 'Oct 14–15, 2026 · 10:00 AM PDT',
    eventVenue: 'Pier 48, San Francisco, CA & Global Investor Stream',
    eventCalendarUrl: 'https://www.ycombinator.com/demoday/',
    uploader: {
      id: 'user-head-admin',
      name: 'Elena Rostova',
      role: 'admin',
    },
    status: 'approved',
    automatedCheck: {
      urlResolves: true,
      dateRecent: true,
      categoryMatch: true,
      flagged: false,
      flagReasons: [],
      checkedAt: '2026-09-20T11:05:00.000Z',
      httpStatus: 200,
    },
    createdAt: '2026-09-20T11:05:00.000Z',
    sourceType: 'contributor-submission',
  },

  // 6. Funding Route / Education Card
  {
    id: 'news-3',
    category: 'funding-routes',
    headline: 'Venture Debt vs. SAFE Convertible Notes in 2026: Balancing Runway Without Down-Rounds',
    sourceName: 'Forbes Tech Council',
    sourceUrl: 'https://www.forbes.com/business/',
    publishDate: '2026-09-19T16:00:00.000Z',
    summary: 'Silicon Valley lenders and structured finance partners outline practical benchmarks for Series A and B startups utilizing revenue-backed debt covenants to extend cash runway without pricing dilutive equity rounds.',
    imageUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&auto=format&fit=crop&q=80',
    fundingAmount: '$5,000,000 – $25,000,000',
    fundingRound: 'Venture Debt Benchmark',
    investors: ['Silicon Valley Bridge Partners', 'Hercules Capital', 'Trinity Capital'],
    uploader: {
      id: 'user-head-admin',
      name: 'Elena Rostova',
      role: 'admin',
    },
    status: 'approved',
    automatedCheck: {
      urlResolves: true,
      dateRecent: true,
      categoryMatch: true,
      flagged: false,
      flagReasons: [],
      checkedAt: '2026-09-19T16:05:00.000Z',
      httpStatus: 200,
    },
    createdAt: '2026-09-19T16:05:00.000Z',
    sourceType: 'automated-ingestion',
  },

  // 7. Scheme Card: SBA Fast Track
  {
    id: 'news-7',
    category: 'new-schemes',
    headline: 'US SBA Unveils $500M Fast-Track Innovation Grant Pilot for Hardware Startups',
    sourceName: 'U.S. Small Business Administration',
    sourceUrl: 'https://www.sba.gov/funding-programs/grants',
    publishDate: '2026-09-18T13:00:00.000Z',
    summary: 'The new grant window removes matching-fund mandates for domestic manufacturing robotics and prototype battery testbeds under Phase I SBIR waivers.',
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80',
    schemeOfferedBy: 'U.S. Small Business Administration (SBA)',
    schemeDeadline: 'November 30, 2026',
    schemeApplyUrl: 'https://www.sba.gov/funding-programs/grants',
    uploader: {
      id: 'user-contributor-2',
      name: 'Dr. Sarah Jenkins',
      role: 'uploader',
    },
    status: 'approved',
    automatedCheck: {
      urlResolves: true,
      dateRecent: true,
      categoryMatch: true,
      flagged: false,
      flagReasons: [],
      checkedAt: '2026-09-18T13:10:00.000Z',
      httpStatus: 200,
    },
    createdAt: '2026-09-18T13:10:00.000Z',
    sourceType: 'automated-ingestion',
  },

  // 8. Pending uploader submission for verification demo
  {
    id: 'news-pending-1',
    category: 'investor-activity',
    headline: 'Nordic CleanGrid Closes €14.5M Seed Round to Deploy Dynamic Transformer Sensors',
    sourceName: 'Sifted EU',
    sourceUrl: 'https://sifted.eu/articles',
    publishDate: '2026-09-22T21:00:00.000Z',
    summary: 'Stockholm startup announces funding led by Pale Blue Dot to roll out high-voltage transmission monitoring units across Scandinavia.',
    imageUrl: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&auto=format&fit=crop&q=80',
    fundingAmount: '€14,500,000',
    fundingRound: 'Seed',
    investors: ['Pale Blue Dot', 'Norrsken VC'],
    uploader: {
      id: 'user-contributor-2',
      name: 'Dr. Sarah Jenkins',
      role: 'uploader',
    },
    status: 'pending',
    automatedCheck: {
      urlResolves: true,
      dateRecent: true,
      categoryMatch: true,
      flagged: false,
      flagReasons: [],
      checkedAt: '2026-09-22T21:05:00.000Z',
      httpStatus: 200,
    },
    createdAt: '2026-09-22T21:05:00.000Z',
    sourceType: 'contributor-submission',
  },
];

export const INITIAL_EVENTS: StartupEvent[] = [
  {
    id: 'event-1',
    name: 'TechCrunch Disrupt 2026 — Startup Battlefield 200',
    dateTime: 'Oct 28–30, 2026 · 09:00 AM PDT',
    venue: 'Moscone Center West, San Francisco, CA',
    organizer: 'TechCrunch Events',
    sourceUrl: 'https://techcrunch.com/events/tc-disrupt-2026/',
    description: 'The premier annual pitch competition where 200 curated early-stage startups compete on the main stage in front of top venture capitalists and press.',
    type: 'pitch-day',
    isOnline: false,
  },
  {
    id: 'event-2',
    name: 'Y Combinator Fall Global Demo Day',
    dateTime: 'Oct 14–15, 2026 · 10:00 AM PDT',
    venue: 'Pier 48, San Francisco & Live Investor Stream',
    organizer: 'Y Combinator',
    sourceUrl: 'https://www.ycombinator.com/demoday/',
    description: 'Official two-day presentation of the newest YC founder batch. 1-minute live founder pitches followed by direct 1:1 investor intro portal access.',
    type: 'demo-day',
    isOnline: true,
  },
  {
    id: 'event-3',
    name: 'Slush 2026 — European DeepTech & Founder Showcase',
    dateTime: 'Nov 19–20, 2026 · 08:30 AM EET',
    venue: 'Messukeskus Expo Hall, Helsinki, Finland',
    organizer: 'Slush Non-profit Community',
    sourceUrl: 'https://slush.org/',
    description: 'The world’s most concentrated gathering of venture capital and high-growth founders, featuring curated founder-investor speed meetings and policy roundtables.',
    type: 'expo',
    isOnline: false,
  },
  {
    id: 'event-4',
    name: 'AWS Global Generative AI Accelerator — Batch 4 Pitch Day',
    dateTime: 'Oct 14, 2026 · 02:00 PM EDT',
    venue: 'Virtual Global Broadcast (Online)',
    organizer: 'Amazon Web Services & Accel',
    sourceUrl: 'https://aws.amazon.com/startups/accelerators',
    description: 'Virtual pitch showcase featuring 30 pre-seed and seed founders deploying foundation models in healthcare, manufacturing, and spatial robotics.',
    type: 'pitch-day',
    isOnline: true,
  },
  {
    id: 'event-5',
    name: 'Techstars London Winter Batch Application Deadline',
    dateTime: 'Oct 05, 2026 · 11:59 PM GMT',
    venue: 'Online Application Portal',
    organizer: 'Techstars Worldwide Network',
    sourceUrl: 'https://www.techstars.com/accelerators/london',
    description: 'Final submission cutoff for the 13-week mentor-driven accelerator program providing $120k initial investment, workspace, and global investor demo day.',
    type: 'accelerator-deadline',
    isOnline: true,
  },
];

export const INITIAL_MESSAGES: ChatMessage[] = [
  {
    id: 'msg-1',
    senderId: 'user-contributor-1',
    recipientId: 'user-viewer-default',
    content: 'Hi Alex! Saw you are working on generative workflow automation. Have you explored applying for the EIC DeepTech scheme or are you targeting US angels first?',
    createdAt: '2026-09-22T15:20:00.000Z',
    read: true,
  },
  {
    id: 'msg-2',
    senderId: 'user-viewer-default',
    recipientId: 'user-contributor-1',
    content: 'Hey Marcus! We just closed our pre-seed angel syndication last week, but we are looking at non-dilutive grants for our European subsidiary. Thanks for sharing the EIC update on the feed!',
    createdAt: '2026-09-22T15:35:00.000Z',
    read: true,
  },
  {
    id: 'msg-3',
    senderId: 'user-head-admin',
    recipientId: 'user-viewer-default',
    content: 'Welcome to VenturePulse Alex! Let us know if you have real verified launch news when your product ships.',
    createdAt: '2026-09-22T16:00:00.000Z',
    read: false,
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    userId: 'user-viewer-default',
    title: 'New Message from Elena Rostova',
    body: 'Welcome to VenturePulse Alex! Let us know if you have real verified launch news...',
    createdAt: '2026-09-22T16:00:00.000Z',
    read: false,
    type: 'chat',
    linkTarget: {
      tab: 'chat',
      chatWithUserId: 'user-head-admin',
    },
  },
  {
    id: 'notif-2',
    userId: 'user-viewer-default',
    title: 'New Scheme Verified: EU EIC €1.4B Fund',
    body: 'A new approved program was published in New Schemes.',
    createdAt: '2026-09-21T09:20:00.000Z',
    read: true,
    type: 'news_approved',
    linkTarget: {
      tab: 'feed',
      itemId: 'news-2',
    },
  },
];
